### ISSUE TITLE
[Ompl Planner] Planning failed

### ISSUE THREAD

**Issue by JiaWenHa** [VIS4ROB-lab/dmce#1]
When I run the program, the following prompt appears in the terminal，I don't know if this is normal:
![image](https://github.com/VIS4ROB-lab/dmce/assets/108913515/17349e0a-d5fc-4219-856c-8444ea962c94)

**Comment by seanbone** [comment]
Hi,
This may happen depending in the configuration, map, starting conditions and destination OMPL is being asked to path towards. Try checking the start and destination locations and see if there actually is a feasible path on the map you're using.

Bear in mind that the pathfinding map is a modified version of the ground truth - obstacles are inflated to account for the robot's dimensions. This may cause tight passages to become blocked on the planning map.

Also, I can't remember exactly how this is handled in the code, but there is a maximum timeout on the amount of time OMPL is allowed for planning. So, if you're using a very large or topologically complex map, it might be unable to find a path even if one exists. Similar issues might arise due to insufficient computational resources - if that is the case, here are some ideas for mitigation:
- use fewer agents (try just 1)
- use a smaller (lower resolution) map
- slow the simulation time

Finally, the OMPL pathfinder uses an RRT-based pathfinding algorithm. This means it occasionally may just fail due to bad luck or unfortunate circumstance. The occasional planning failure is okay and the simulator is built to account for it. It's only an issue if it happens too frequently.

I hope these tips can help you debug, let me know if there are further issues!
